# Generated by Django 4.1.2 on 2022-11-02 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="date_of_birth",),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="followings",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mbti",
            field=models.CharField(default=True, max_length=4),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
