# Generated by Django 4.1.2 on 2022-11-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_date_of_birth_user_bio_user_followings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default=True, max_length=20, unique=True),
        ),
    ]
