# Generated by Django 4.1.2 on 2022-11-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_bio_alter_user_email_alter_user_mbti_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=255, unique=True
            ),
        ),
    ]
