# Generated by Django 4.1.2 on 2022-11-05 17:10

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
