# Generated by Django 4.1.2 on 2022-11-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('poster', models.TextField()),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
